### ISSUE TITLE
"%prec" isn't been accepted

### ISSUE THREAD

**Issue by mingodad** [BenHanson/gram_grep#2]
While trying to convert `PostgreSQL-16` to a grammar accepted by this project I found that the `%prec` attribute is not accepted/parsed and then I converted the bison calculator example shown here http://benhanson.net/parsertl.html and it also is not accepted:
```
// Calculator from flex & bison book.
//Directives
%token INTEGER
%left '+' '-'
%left '*' '/'
%precedence UMINUS

%% //Grammar rules
start : exp ;
exp : exp '+' exp ;
exp : exp '-' exp ;
exp : exp '*' exp ;
exp : exp '/' exp ;
exp : '(' exp ')' ;
exp : '-' exp %prec UMINUS ;
exp : INTEGER ;

%% //Regex macros

%% //Regex rules

[0-9]+	INTEGER

%% //End
```
Output:
```
gram-grep -f "calculator.g" main.cpp
Parse error in calculator.g at line 15, column 15
Command exited with non-zero status 1
```

**Comment by mingodad** [comment]
Adding this code to dump the lexer tokens:
```
while(iter->id != 0) {std::cout << iter->id << " : " << iter->str() << "\n"; ++iter;}
```
It seems that it's not recognizing `%prec` but `%` and `prec` :
```
...
8 : exp
26 : :
5 : '-'
8 : exp
65535 : %
8 : prec
8 : UMINUS
27 : ;
8 : exp
26 : :
8 : INTEGER
...
```

**Comment by mingodad** [comment]
Adding this lexer rule to `void build_config_parser()` seems to fix the problem:
```
...
    lrules.push("GRULE", ":", grules.token_id("':'"), ".");
    lrules.push("GRULE", "%prec", grules.token_id("'%prec'"), "."); //!!<< adding this missing rule
    lrules.push("GRULE", "\\[", grules.token_id("'['"), ".");
...
```

**Comment by mingodad** [comment]
But `PostgreSQL` grammar uses `%prec` on an empty rule but right now this project do not accept it:
```
...
opt_existing_window_name :
	ColId
	| %empty %prec Op /*16L*/
	;
...
```

**Comment by mingodad** [comment]
Testing the php `read_bison` with this grammar:
```
<?php
use Parle\Parser;

$p = new Parser;

$heredoc_grammar = <<<HEREA
%token INTEGER
%precedence UMINUS

%% //Grammar rules
start :
	INTEGER
	| %empty %prec UMINUS
	;
%%
HEREA;

$p->readBison($heredoc_grammar);


$p->dump();

try
{
	$p->readBison("@");
}
catch (\Throwable $e)
{
	echo $e->getMessage(), "\n";
}
?>
```
Also gives this error:
```
php -f "test-empty-prec.y.php"
PHP Fatal error:  Uncaught Parle\ParserException: Syntax error in rule 'start': 'INTEGER
	| %empty %prec UMINUS'. in test-empty-prec.y.php:18
Stack trace:
#0 test-empty-prec.y.php(18): Parle\Parser->readBison('%token INTEGER\r...')
#1 {main}
  thrown in test-empty-prec.y.php on line 18

Fatal error: Uncaught Parle\ParserException: Syntax error in rule 'start': 'INTEGER
	| %empty %prec UMINUS'. in test-empty-prec.y.php:18
Stack trace:
#0 test-empty-prec.y.php(18): Parle\Parser->readBison('%token INTEGER\r...')
#1 {main}
  thrown in test-empty-prec.y.php on line 18
```

**Comment by mingodad** [comment]
I could fix the `Warning: Token "UMINUS" is not used in the grammar.` with the code shown bellow: 
```
@@ -371,6 +386,18 @@ struct config_state
 
             for (const auto& p : grammar)
             {
+                //Add %prec TOKEN to the list of used terminals
+                if (!p._rhs.second.empty())
+                {
+                    const auto pos = std::find( terminals.begin()
+                                                     , terminals.end()
+                                                     , p._rhs.second );
+                    if( pos != terminals.end() ) {
+                        size_t idx = pos-terminals.begin();
+                        used_tokens.insert(idx);
+                    }
+                    
+                }
                 for (const auto& rhs : p._rhs.first)
                 {
                     if (rhs._type == parsertl::rules::symbol::type::TERMINAL)
```

**Comment by BenHanson** [comment]
Done
